### PR TITLE
Add linters and formatter configuration and apply changes from them.

### PR DESCRIPTION
**Pull request by parona-source**
I know black formatter is opinionated and some don't like it due to that, but some followed format is better than no format.

This is just low hanging fruit with applying black, isort and ruff where applicable.

### CODE REVIEW

**Comment by hartwork** [comment]
@parona-source thanks!

**Comment by hartwork** [comment]
@parona-source PS: I'll add GitHub Actions CI based on pre-commit now, fix the license to be GPL-2+ rather than GPL-2 only, add a `.mailmap` file to merge my two identities and do a pull request adding more of the past authors. Probably all as a pull request. What would be a good threshold for commit count to add — 1 or more?

**Comment by hartwork** [comment]
@parona-source update on progress:
- Pull request #18
- Pull request #19
- Commit b4ac8abd4d2d5f71fe84f65067ec959b8a088376 for `.mailmap`

**Comment by parona-source** [comment]
>  ... and do a pull request adding more of the past authors. Probably all as a pull request. What would be a good threshold for commit count to add — 1 or more?

I guess going with if the someone has modified the file to be good enough metric. Better to have too many than omit someone because they didn't pass an arbitrary metric.

I'm mostly thinking that someone *could* do a drive by commit with a considerable feature or fix  which would just be one commit and excluding them would seem backwards.

**Pull request merged**
